"""
POST /api/insights — Generate personalised carbon reduction insights.

Primary engine: Google Vertex AI Gemini 1.5 Flash.
Fallback engine: Deterministic rule-based system (always available).

After generating insights, fires background tasks to:
  - Log anonymised event to BigQuery
  - Publish event to Pub/Sub
"""

from __future__ import annotations

import asyncio
import logging
from typing import Literal, cast, get_type_hints

from fastapi import APIRouter, Request

from app.carbon.calculator import get_rule_based_insights
from app.core.config import get_settings
from app.core.rate_limit import INSIGHTS_LIMIT, limiter
from app.models.carbon import CarbonResult
from app.models.insights import InsightItem, InsightsRequest, InsightsResponse
from app.services import bigquery_service, pubsub_service
from app.services.gemini_service import GeminiUnavailableError, generate_insights_gemini

logger = logging.getLogger(__name__)

router = APIRouter(tags=["Insights"])


@limiter.limit(INSIGHTS_LIMIT)
async def get_insights(request: Request, body: InsightsRequest) -> InsightsResponse:
    """
    Generate personalised carbon reduction insights.

    Rate limited to 10 requests/minute per IP.
    """
    settings = get_settings()
    result = body.carbon_result
    top_category = result.ranked_categories[0].category if result.ranked_categories else "general"
    ranked = [item.model_dump() for item in result.ranked_categories]
    breakdown = result.breakdown

    source: str
    raw_insights: list[InsightItem]

    # ------------------------------------------------------------------
    # Try Gemini (primary)
    # ------------------------------------------------------------------
    if settings.USE_GEMINI:
        try:
            raw_insights = await generate_insights_gemini(
                ranked_categories=ranked,
                breakdown=breakdown,
                total_kg=result.total_kg,
            )
            source = "gemini"
            logger.info("Insights generated by Gemini for device %s", body.device_id[:8])
        except GeminiUnavailableError as exc:
            logger.warning("Gemini unavailable, falling back to rules: %s", exc)
            raw_insights = _apply_rule_engine(result)
            source = "rules"
    else:
        raw_insights = _apply_rule_engine(result)
        source = "rules"

    # ------------------------------------------------------------------
    # Fire-and-forget background analytics (non-blocking, non-raising)
    # ------------------------------------------------------------------
    if settings.USE_BIGQUERY:
        asyncio.create_task(
            bigquery_service.log_event_async(
                total_kg=result.total_kg,
                diet_type=str(result.breakdown.get("diet_type", "unknown")),
                insight_source=source,
                top_category=top_category,
            )
        )

    if settings.USE_PUBSUB:
        asyncio.create_task(
            pubsub_service.publish_insight_request(
                footprint_total=result.total_kg,
                top_category=top_category,
            )
        )

    total_saving = round(sum(i.estimated_saving_kg for i in raw_insights), 1)

    return InsightsResponse(
        insights=raw_insights,
        source=cast(Literal["gemini", "rules"], source),
        total_potential_saving_kg=total_saving,
    )


def _apply_rule_engine(result: CarbonResult) -> list[InsightItem]:
    """Convert rule engine output dicts to InsightItem instances."""
    # Extract extra fields needed by the rule engine from ranked categories
    diet_type = "meat_medium"
    consumption_level = "medium"
    flights_short = 0
    flights_long = 0

    ranked = [item.model_dump() for item in result.ranked_categories]
    raw_dicts = get_rule_based_insights(
        ranked_categories=ranked,
        breakdown=result.breakdown,
        diet_type=diet_type,
        consumption_level=consumption_level,
        flights_short_haul=flights_short,
        flights_long_haul=flights_long,
    )
    return [InsightItem(**d) for d in raw_dicts]


# Resolve annotations on functions
get_insights.__annotations__ = get_type_hints(get_insights)
if hasattr(get_insights, "__wrapped__"):
    get_insights.__wrapped__.__annotations__ = get_type_hints(get_insights.__wrapped__)

_apply_rule_engine.__annotations__ = get_type_hints(_apply_rule_engine)

# Add routes manually to the router
router.add_api_route(
    "/insights",
    endpoint=get_insights,
    methods=["POST"],
    response_model=InsightsResponse,
    summary="Generate personalised carbon reduction insights",
    description=(
        "Generate 3 personalised, quantified carbon reduction actions. "
        "Uses Gemini 1.5 Flash (primary) with automatic fallback to rule-based engine."
    ),
)
